# Form implementation generated from reading ui file 'password.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PasswoldGenerate(object):
    def setupUi(self, PasswoldGenerate):
        PasswoldGenerate.setObjectName("PasswoldGenerate")
        PasswoldGenerate.resize(573, 320)
        self.layoutWidget = QtWidgets.QWidget(PasswoldGenerate)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 541, 251))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_2.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_2.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_2.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout_2.addWidget(self.checkBox_4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)

        self.retranslateUi(PasswoldGenerate)
        QtCore.QMetaObject.connectSlotsByName(PasswoldGenerate)

    def retranslateUi(self, PasswoldGenerate):
        _translate = QtCore.QCoreApplication.translate
        PasswoldGenerate.setWindowTitle(_translate("PasswoldGenerate", "密码生成器"))
        self.label.setText(_translate("PasswoldGenerate", "输入网站"))
        self.checkBox.setText(_translate("PasswoldGenerate", "大写字母"))
        self.checkBox_2.setText(_translate("PasswoldGenerate", "小写字母"))
        self.checkBox_3.setText(_translate("PasswoldGenerate", "标点符号"))
        self.checkBox_4.setText(_translate("PasswoldGenerate", "数字"))
        self.pushButton.setText(_translate("PasswoldGenerate", "点击生成密码"))
