# Form implementation generated from reading ui file 'weather.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_weather(object):
    def setupUi(self, weather):
        weather.setObjectName("weather")
        weather.resize(332, 377)
        self.widget = QtWidgets.QWidget(weather)
        self.widget.setGeometry(QtCore.QRect(30, 80, 258, 233))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.textBrowser = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)

        self.retranslateUi(weather)
        QtCore.QMetaObject.connectSlotsByName(weather)

    def retranslateUi(self, weather):
        _translate = QtCore.QCoreApplication.translate
        weather.setWindowTitle(_translate("weather", "天气查询"))
        self.comboBox.setItemText(0, _translate("weather", "温州"))
        self.comboBox.setItemText(1, _translate("weather", "宁波"))
        self.pushButton.setText(_translate("weather", "查询"))
