# Form implementation generated from reading ui file 'scanwifi.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets



class Ui_ScanWifi(object):
    def setupUi(self, ScanWifi):
        ScanWifi.setObjectName("ScanWifi")
        ScanWifi.resize(507, 563)
        self.layoutWidget = QtWidgets.QWidget(ScanWifi)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 60, 343, 431))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.listView = QtWidgets.QListView(self.layoutWidget)
        self.listView.setObjectName("listView")
        self.verticalLayout.addWidget(self.listView)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)

        self.retranslateUi(ScanWifi)
        QtCore.QMetaObject.connectSlotsByName(ScanWifi)

    def retranslateUi(self, ScanWifi):
        _translate = QtCore.QCoreApplication.translate
        ScanWifi.setWindowTitle(_translate("ScanWifi", "wifi密码破解器"))
        self.pushButton.setText(_translate("ScanWifi", "开始扫描"))
        self.pushButton_2.setText(_translate("ScanWifi", "破解密码"))
